#### Stage 1: Build the application
FROM maven as builder
WORKDIR /usr/src/mymaven
COPY spring-boot /usr/src/mymaven
RUN mvn -f spring-boot-samples/spring-boot-sample-web-static/pom.xml clean install


FROM tomcat
WORKDIR /app

COPY --from=builder /usr/src/mymaven/spring-boot-samples/spring-boot-sample-web-static/target/*war /usr/local/tomcat/webapps/web-static.war
EXPOSE 8080

