#### Stage 1: Build the application
FROM maven:3.6.2 as builder
WORKDIR /usr/src/mymaven
COPY spring-boot /usr/src/mymaven
RUN mvn -f spring-boot-samples/spring-boot-sample-web-ui/pom.xml clean install	

#### Stage 2: A minimal docker image with command to run the app
FROM openjdk:8-jre-alpine
WORKDIR /app

COPY  --from=builder /usr/src/mymaven/spring-boot-samples/spring-boot-sample-web-ui/target/*jar web-ui.jar
EXPOSE 8080
CMD exec java $JAVA_OPTS -jar /app/web-ui.jar --server.servlet.context-path=/ui