#### Stage 1: Build the application
FROM maven:3.6.2 as builder
WORKDIR /usr/src/mymaven
COPY spring-boot /usr/src/mymaven
RUN mvn -f spring-boot-samples/spring-boot-sample-web-static/pom.xml clean install


FROM tomcat:8.5.47
RUN rm -fr /usr/local/tomcat/webapps/ROOT.war
RUN rm -fr /usr/local/tomcat/webapps/ROOT/
COPY --from=builder /usr/src/mymaven/spring-boot-samples/spring-boot-sample-web-static/target/*war /usr/local/tomcat/webapps/ROOT.war
EXPOSE 8080

