version: "3.5"
services:
 web-static:
  build:
   context: .
   dockerfile: Dockerfile-apps
   target: web-static
  
 web-ui:
  build:
   context: .
   dockerfile: Dockerfile-apps
   target: web-ui
  
 proxy:
  build:
   context: .
   dockerfile: Dockerfile-haproxy
  ports:
   - "9000:9000"
  depends_on:
   - "web-ui"
   - "web-static"
