version: "3"
services:
 web-ui:
  build:
   context: .
   dockerfile: Dockerfile-web-ui
  ports:
  - "8080:8080"

 web-static:
  build:
   context: .
   dockerfile: Dockerfile-web-static
  ports:
  - "8081:8080"

 proxy:
  build:
   context: .
   dockerfile: Dockerfile-haproxy
  ports:
  - "9000:8080"
  